package com.localon.course;
import com.localon.auth.AuthService; import com.localon.common.NotFoundException; import com.localon.place.PlaceService; import com.localon.region.RegionService; import jakarta.validation.constraints.*; import lombok.RequiredArgsConstructor; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api/courses") @RequiredArgsConstructor public class SavedCourseController {
 private final SavedCourseRepository repo; private final AuthService auth; private final RegionService regions; private final PlaceService places;
 @GetMapping @Transactional(readOnly=true) public List<Response> list(){var u=auth.current();return repo.findByUser_IdOrderByCreatedAtDesc(u.getId()).stream().map(this::response).toList();}
 @GetMapping("/{id}") @Transactional(readOnly=true) public Response one(@PathVariable Long id){var u=auth.current();return response(repo.findByIdAndUser_Id(id,u.getId()).orElseThrow(()->new NotFoundException("저장 코스를 찾을 수 없습니다.")));}
 @PostMapping public Response create(@jakarta.validation.Valid @RequestBody Request r){var u=auth.current();var c=new SavedCourse();c.setUser(u);c.setRegion(regions.resolve(r.regionId()));c.setTitle(r.title()==null||r.title().isBlank()?c.getRegion().getName()+" 여행 코스":r.title());c.setLocalRatio(r.localRatio());c.setDurationCode(r.duration());c.setThemes(r.selectedThemes()==null?new ArrayList<>():new ArrayList<>(r.selectedThemes()));c.setPlaceIds(r.placeIds()==null?new ArrayList<>():new ArrayList<>(r.placeIds()));return response(repo.save(c));}
 @PostMapping("/{id}/places/{placeId}") public Response addPlace(@PathVariable Long id,@PathVariable String placeId){var u=auth.current();places.entity(placeId);var c=repo.findByIdAndUser_Id(id,u.getId()).orElseThrow(()->new NotFoundException("저장 코스를 찾을 수 없습니다."));if(!c.getPlaceIds().contains(placeId))c.getPlaceIds().add(placeId);return response(repo.save(c));}
 @DeleteMapping("/{id}/places/{placeId}") public Response removePlace(@PathVariable Long id,@PathVariable String placeId){var u=auth.current();var c=repo.findByIdAndUser_Id(id,u.getId()).orElseThrow(()->new NotFoundException("저장 코스를 찾을 수 없습니다."));c.getPlaceIds().remove(placeId);return response(repo.save(c));}
 @DeleteMapping("/{id}") public void delete(@PathVariable Long id){var u=auth.current();repo.delete(repo.findByIdAndUser_Id(id,u.getId()).orElseThrow(()->new NotFoundException("저장 코스를 찾을 수 없습니다.")));}
 private Response response(SavedCourse c){return new Response(c.getId(),c.getTitle(),c.getRegion().getName(),c.getLocalRatio(),c.getDurationCode(),new ArrayList<>(c.getThemes()),new ArrayList<>(c.getPlaceIds()),c.getCreatedAt());}
 public record Request(@NotBlank String regionId,String title,@Min(0) @Max(100) int localRatio,List<String> selectedThemes,String duration,List<String> placeIds){}
 public record Response(Long id,String title,String regionName,int localRatio,String duration,List<String> selectedThemes,List<String> placeIds,Instant createdAt){}
}
